# Generated by Django 3.0.8 on 2020-07-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('namespace', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('active', models.BooleanField(default=True)),
                ('space_page_url', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('directory_URL', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('icon_URL', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
