# Generated by Django 3.0.8 on 2020-07-30 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenttype',
            old_name='space_page_url',
            new_name='space_page_URL',
        ),
    ]
