# Generated by Django 3.0.8 on 2020-08-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.CharField(max_length=2000)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='space_images')),
                ('type', models.CharField(choices=[('CRUD', 'CRUD'), ('CRUD_LIST', 'CRUD List'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('url', models.CharField(default='', max_length=128)),
                ('show_application_menu', models.BooleanField(default=False)),
                ('show_space_menu', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
            ],
        ),
    ]
