# Generated by Django 3.0.8 on 2020-08-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_positions', '0007_auto_20200824_2238'),
        ('api_programs', '0002_auto_20200825_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='private_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='program',
            name='public_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='restricted_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='restricted_to_roles',
            field=models.ManyToManyField(blank=True, related_name='position_programs', to='api_positions.Position'),
        ),
    ]
