# Generated by Django 3.0.8 on 2020-08-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_programs', '0003_auto_20200825_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='restricted_to_roles',
            new_name='restricted_to_positions',
        ),
    ]
