# Generated by Django 3.0.8 on 2020-08-25 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_positions', '0007_auto_20200824_2238'),
        ('api_groups', '0001_initial'),
        ('api_spaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='admin_role',
        ),
        migrations.RemoveField(
            model_name='space',
            name='restricted_to_roles',
        ),
        migrations.AddField(
            model_name='space',
            name='admin_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_position_spaces', to='api_positions.Position'),
        ),
        migrations.AddField(
            model_name='space',
            name='restricted_to_groups',
            field=models.ManyToManyField(blank=True, related_name='group_spaces', to='api_groups.Group'),
        ),
        migrations.AddField(
            model_name='space',
            name='restricted_to_positions',
            field=models.ManyToManyField(blank=True, related_name='position_spaces', to='api_positions.Position'),
        ),
        migrations.AlterField(
            model_name='space',
            name='admin_method',
            field=models.CharField(choices=[('POSITION', 'A specific position'), ('USER', 'A specific user'), ('WEBADMIN', 'Website Administrator')], default='POSITION', max_length=20),
        ),
    ]
