# Generated by Django 3.0.8 on 2020-08-31 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_spaces', '0002_auto_20200825_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, height_field='picture_height', null=True, upload_to='walls/', width_field='picture_width')),
                ('picture_height', models.IntegerField(blank=True, default=0, null=True)),
                ('picture_width', models.IntegerField(blank=True, default=0, null=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('message', models.TextField(blank=True, default='', null=True)),
                ('content_app_id', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('content_pk', models.IntegerField(default=0)),
                ('created_dateTime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='wall_dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='wall_likes', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_spaces.Space')),
            ],
            options={
                'ordering': ['-created_dateTime'],
            },
        ),
    ]
