# Generated by Django 3.0.8 on 2020-08-20 17:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='membershipProfile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_soronian_sister', models.BooleanField(default=True)),
                ('is_independent', models.BooleanField(default=False)),
                ('is_site_visitor', models.BooleanField(default=False)),
                ('about_me', models.TextField(blank=True, default='')),
                ('picture', models.ImageField(blank=True, height_field='picture_height', upload_to='profile_pics', width_field='picture_width')),
                ('picture_width', models.IntegerField(default=0)),
                ('picture_height', models.IntegerField(default=0)),
                ('pledge_class', models.IntegerField(default=0)),
                ('graduation_year', models.IntegerField(default=0)),
                ('birth_date', models.DateField(blank=True, default=datetime.date(2003, 8, 20), null=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('PROFILED', 'Profiled'), ('ACTIVATED', 'Activated'), ('INACTIVATED', 'Inactivated')], default='REGISTERED', max_length=20)),
                ('is_new_blood', models.BooleanField(default=False)),
                ('profiled', models.BooleanField(default=False)),
                ('profiled_dateTime', models.DateTimeField(blank=True, null=True, verbose_name='Profiled Date/Time')),
                ('validated', models.BooleanField(default=False)),
                ('validated_dateTime', models.DateTimeField(blank=True, null=True, verbose_name='Validated Date/Time')),
                ('activated', models.BooleanField(default=False)),
                ('activated_dateTime', models.DateTimeField(auto_now=True, verbose_name='Actived Date/Time')),
                ('updated_dateTime', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date/Time')),
                ('created_dateTime', models.DateTimeField(auto_now_add=True, verbose_name='Created Date/Time')),
                ('activated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activated_users', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validated_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
