# Generated by Django 3.0.8 on 2020-08-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_positions', '0004_auto_20200819_1015'),
        ('api_members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='house_positions',
            field=models.ManyToManyField(blank=True, related_name='user_positions', to='api_positions.Position', verbose_name='Positions'),
        ),
    ]
