# Generated by Django 3.0.8 on 2020-08-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_members', '0005_auto_20200822_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='type',
            field=models.CharField(choices=[('SISTER', 'I am a Soronian sister.'), ('INDEPENDENT', 'I am a potential Soronian Sister.'), ('VISITOR', 'I am a visitor.')], default='SISTER', max_length=20),
        ),
    ]
