# Generated by Django 3.0.8 on 2020-08-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_members', '0006_member_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_independent',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_site_visitor',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_soronian_sister',
        ),
    ]
