# Generated by Django 3.0.8 on 2020-08-24 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_members', '0008_auto_20200822_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date(2003, 8, 24), null=True),
        ),
    ]
