# Generated by Django 3.0.8 on 2020-08-25 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_members', '0009_auto_20200824_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date(2003, 8, 25), null=True),
        ),
    ]
