# Generated by Django 3.0.8 on 2020-08-26 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_members', '0010_auto_20200825_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date(2003, 8, 26), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='type',
            field=models.CharField(choices=[('ACTIVE', 'I am a Soronian active'), ('NEWBLOOD', 'I am a Soronian new blood'), ('ALUMNI', 'I am a Soronian alumni'), ('INDEPENDENT', 'I might become a Soronian Sister (Independent)')], default='SISTER', max_length=20),
        ),
    ]
