# Generated by Django 3.0.8 on 2020-08-29 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_members', '0013_auto_20200828_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date(2003, 8, 29), null=True),
        ),
    ]
