# Generated by Django 3.0.8 on 2020-08-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_members', '0014_auto_20200829_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='type',
            field=models.CharField(choices=[('ACTIVE', 'I am a Soronian active'), ('ALUMNI', 'I am a Soronian alumni'), ('INDEPENDENT', 'I might become a Soronian Sister (Independent)')], default='SISTER', max_length=20),
        ),
    ]
