# Generated by Django 3.0.8 on 2020-08-30 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_members', '0015_auto_20200829_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date(2003, 8, 30), null=True),
        ),
    ]
