# Generated by Django 3.0.8 on 2020-08-30 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_calendars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('body', models.TextField(blank=True, default='', null=True)),
                ('picture', models.ImageField(blank=True, height_field='picture_height', null=True, upload_to='albums/', width_field='picture_width')),
                ('picture_height', models.IntegerField(blank=True, default=0, null=True)),
                ('picture_width', models.IntegerField(blank=True, default=0, null=True)),
                ('public_body_same_as', models.BooleanField(default=True)),
                ('public_body', models.TextField(blank=True, default='', null=True)),
                ('independent_body_same_as', models.BooleanField(default=True)),
                ('independent_body', models.TextField(blank=True, default='', null=True)),
                ('active_body_same_as', models.BooleanField(default=True)),
                ('active_body', models.TextField(blank=True, default='', null=True)),
                ('alumni_body_same_as', models.BooleanField(default=True)),
                ('alumni_body', models.TextField(blank=True, default='', null=True)),
                ('start_dateTime', models.DateTimeField(null=True, verbose_name='Start time')),
                ('end_dateTime', models.DateTimeField(null=True, verbose_name='End time')),
                ('all_day_event', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='ONCE', max_length=20)),
                ('repeat_every_n_days', models.IntegerField(default=1, verbose_name='Repeat every n-days')),
                ('repeat_every_n_weeks', models.IntegerField(default=1, verbose_name='Repeat every n-weeks')),
                ('repeat_week_of_month', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth')], default='1', max_length=1)),
                ('repeat_on_Mon', models.BooleanField(default=False)),
                ('repeat_on_Tue', models.BooleanField(default=False)),
                ('repeat_on_Wed', models.BooleanField(default=False)),
                ('repeat_on_Thu', models.BooleanField(default=False)),
                ('repeat_on_Fri', models.BooleanField(default=False)),
                ('repeat_on_Sat', models.BooleanField(default=False)),
                ('repeat_on_Sun', models.BooleanField(default=False)),
                ('repeat_last_day_of_month', models.IntegerField(default=1, verbose_name='Last of the month')),
                ('repeat_day_of_the_month', models.IntegerField(default=1, verbose_name='Day of the month')),
                ('repeat_every_n_years', models.IntegerField(default=1, verbose_name='Repeat every n-years')),
                ('end_series', models.CharField(choices=[('NEVER', 'Never'), ('OCCURRENCES', 'After n-occurrences'), ('ENDDATE', 'End date')], default='NEVER', max_length=20)),
                ('series_occurrences', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, default='', max_length=512)),
                ('show_as_busy', models.BooleanField(default=True)),
                ('inherit_space_permissions', models.BooleanField(default=True)),
                ('calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_calendars.Calendar')),
            ],
            options={
                'ordering': ['start_dateTime'],
            },
        ),
    ]
