# Generated by Django 3.0.8 on 2020-08-30 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_eventtypes', '0001_initial'),
        ('api_eventschedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_eventtypes.EventType'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='event_follows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_organizers', to=settings.AUTH_USER_MODEL),
        ),
    ]
