# Generated by Django 3.0.8 on 2020-08-30 23:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_eventschedules', '0002_auto_20200830_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='event_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='event_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
