# Generated by Django 3.0.8 on 2020-08-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventschedules', '0004_eventschedule_weekly_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='repeat_last_day_of_month',
            field=models.BooleanField(default=False),
        ),
    ]
