# Generated by Django 3.0.8 on 2020-09-01 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_eventschedules', '0005_auto_20200830_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='eventschedule_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='eventschedule_follows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='eventschedule_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventschedule_organizers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='picture',
            field=models.ImageField(blank=True, height_field='picture_height', null=True, upload_to='eventschedules/', width_field='picture_width'),
        ),
    ]
