# Generated by Django 3.0.8 on 2020-08-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
