# Generated by Django 3.0.8 on 2020-08-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_albums', '0002_auto_20200828_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='picture_height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='picture_width',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
