# Generated by Django 3.0.8 on 2020-08-14 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_programs', '0001_initial'),
        ('api_spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceLinkList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_menu_items', to='api_spaces.Space')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('sequence', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('ANOTHER_SPACE', 'Link to another Application or Space'), ('CONTENT', 'Link to content'), ('PROGRAM', 'Link to a program'), ('URL', 'Link to an external Url')], default='MENU', max_length=20)),
                ('content_slug', models.SlugField(blank=True, max_length=256, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('icon_URL', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('another_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_links', to='api_spaces.Space')),
                ('link_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api_spacelinks.SpaceLinkList')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='api_spacelinks.SpaceLink')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_links', to='api_programs.Program')),
            ],
        ),
    ]
