# Generated by Django 3.0.8 on 2020-08-14 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_spacelinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacelinklist',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_children', to='api_spacelinks.SpaceLinkList'),
        ),
        migrations.AddField(
            model_name='spacelinklist',
            name='root_link',
            field=models.BooleanField(default=False),
        ),
    ]
