# Generated by Django 3.0.8 on 2020-08-15 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_contenttypes', '0002_auto_20200729_2053'),
        ('api_spacelinks', '0002_auto_20200814_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacelink',
            name='link_list',
        ),
        migrations.AddField(
            model_name='spacelink',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenttype_links', to='api_contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='spacelink',
            name='root_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spacelink',
            name='type',
            field=models.CharField(choices=[('ANOTHER_SPACE', 'Link to another Application or Space'), ('CONTENT', 'Link to content'), ('PROGRAM', 'Link to a program'), ('URL', 'Link to an external Url'), ('FOLDER', 'Folder'), ('SPACER', 'Spacer')], default='MENU', max_length=20),
        ),
        migrations.DeleteModel(
            name='SpaceLinkList',
        ),
    ]
