# Generated by Django 3.0.8 on 2020-08-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_spacelinks', '0004_spacelink_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacelink',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
