# Generated by Django 3.0.8 on 2020-08-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_spacelinks', '0005_auto_20200815_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacelink',
            name='type',
            field=models.CharField(choices=[('ANOTHER_SPACE', 'Link to another Application or Space'), ('CONTENT', 'Link to content'), ('PROGRAM', 'Link to a program'), ('URL', 'Link to an external Url'), ('GROUP_HEADER', 'Group header'), ('FOLDER', 'Folder'), ('SPACER', 'Spacer')], default='MENU', max_length=20),
        ),
    ]
