# Generated by Django 3.0.8 on 2020-08-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content_slug',
            field=models.SlugField(blank=True, default='', max_length=200, null=True),
        ),
    ]
