# Generated by Django 3.0.8 on 2020-08-30 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_spaces', '0002_auto_20200825_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('body', models.TextField()),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_spaces.Space')),
            ],
        ),
    ]
