# Generated by Django 3.0.8 on 2020-08-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_positions', '0004_auto_20200819_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('positions', models.ManyToManyField(blank=True, to='api_positions.Position')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
