# Generated by Django 3.0.8 on 2020-07-30 03:42

import colorful.fields
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, default='', max_length=200)),
                ('domain_name', models.CharField(blank=True, default='', max_length=200)),
                ('site_email_address', models.EmailField(blank=True, default='', max_length=256)),
                ('site_phone_number', phone_field.models.PhoneField(blank=True, help_text='Site phone number', max_length=31)),
                ('main_background_color', colorful.fields.RGBColorField()),
                ('primary_color', colorful.fields.RGBColorField()),
                ('primary_light_color', colorful.fields.RGBColorField()),
                ('secondary_color', colorful.fields.RGBColorField()),
                ('secondary_light_color', colorful.fields.RGBColorField()),
                ('brand_logo_img', models.ImageField(blank=True, null=True, upload_to='config_images')),
                ('header_background_img', models.ImageField(blank=True, null=True, upload_to='config_images')),
                ('log_in_img', models.ImageField(blank=True, null=True, upload_to='config_images')),
                ('sign_up_img', models.ImageField(blank=True, null=True, upload_to='config_images')),
                ('change_password_img', models.ImageField(blank=True, null=True, upload_to='config_images')),
                ('reset_password_img', models.ImageField(blank=True, null=True, upload_to='config_images')),
                ('successful_sign_up_msg', models.TextField(default='Thank you for signing up!')),
                ('acceptable_use_policy', models.TextField()),
            ],
        ),
    ]
