# Generated by Django 3.0.8 on 2020-07-30 00:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.CharField(max_length=2000)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles_images', verbose_name='Image')),
                ('image_size', models.CharField(choices=[('NORMAL', 'Normal'), ('BIG', 'Big'), ('TALL', 'Tall'), ('WIDE', 'Wide')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE_NOTPUBLISHED', 'Active (Not published)'), ('ACTIVE_PUBLISHED', 'Active (Published)'), ('INACTIVE_EXPIRED', 'Inactive (Expired)'), ('INACTIVE_ARCHIVED', 'Inactive (Archived)'), ('INACTIVE_REMOVED', 'Inactive (Removed)')], default='DRAFT', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('featured_start_dateTime', models.DateField(blank=True, null=True, verbose_name='Featured Start')),
                ('featured_end_dateTime', models.DateField(blank=True, null=True, verbose_name='Featured End')),
                ('required_reading', models.BooleanField(default=False)),
                ('publication_dateTime', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Publication')),
                ('expiration_dateTime', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Expiration')),
                ('read_dateTime', models.DateTimeField(blank=True, null=True, verbose_name='Last read')),
                ('updated_dateTime', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('created_dateTime', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('inherit_parent_permissions', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='article_dislikes', to=settings.AUTH_USER_MODEL)),
                ('follows', models.ManyToManyField(blank=True, related_name='article_follows', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='article_likes', to=settings.AUTH_USER_MODEL)),
                ('reads', models.ManyToManyField(blank=True, related_name='article_reads', to=settings.AUTH_USER_MODEL)),
                ('related_content', models.ManyToManyField(blank=True, related_name='_article_related_content_+', to='api_articles.Article')),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_spaces.Space')),
            ],
            options={
                'ordering': ['-created_dateTime'],
            },
        ),
    ]
