# Generated by Django 3.0.8 on 2020-08-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_positions', '0003_position_is_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='parent_positions',
            field=models.ManyToManyField(blank=True, related_name='child_positions', to='api_positions.Position', verbose_name='Parent Positions'),
        ),
    ]
