# Generated by Django 3.0.8 on 2020-08-24 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_positions', '0004_auto_20200819_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='is_group',
            new_name='is_top_five',
        ),
        migrations.RemoveField(
            model_name='position',
            name='parent_positions',
        ),
        migrations.AddField(
            model_name='position',
            name='parent_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_positions.Position'),
        ),
    ]
