# Generated by Django 3.0.8 on 2020-08-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_positions', '0005_auto_20200824_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='parent_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_positions.Position'),
        ),
    ]
