# Generated by Django 3.0.8 on 2020-08-28 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('summary', models.CharField(max_length=2000)),
                ('picture', models.ImageField(blank=True, height_field='picture_height', null=True, upload_to='photos/', width_field='picture_width')),
                ('picture_height', models.IntegerField(default=0)),
                ('picture_width', models.IntegerField(default=0)),
                ('inherit_parent_permissions', models.BooleanField(default=True)),
                ('updated_dateTime', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('created_dateTime', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_albums.Album')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='photo_dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='photo_likes', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_uploads', to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(blank=True, related_name='photo_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
